# Generated by Django 4.2.7 on 2023-11-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="tags", options={},),
        migrations.AlterModelTable(name="post", table=None,),
        migrations.AlterModelTable(name="postcomments", table=None,),
        migrations.AlterModelTable(name="postdownload", table=None,),
        migrations.AlterModelTable(name="postreport", table=None,),
        migrations.AlterModelTable(name="profile", table=None,),
        migrations.AlterModelTable(name="subject", table=None,),
        migrations.AlterModelTable(name="tags", table=None,),
        migrations.AlterModelTable(name="userfollower", table=None,),
    ]
