# Generated by Django 4.2.4 on 2023-11-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
