# Generated by Django 4.2.5 on 2023-10-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_reason", models.CharField(max_length=200)),
                (
                    "report_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date reported"
                    ),
                ),
                ("report_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name="usercomment", name="user",),
        migrations.RenameField(
            model_name="post", old_name="post_text", new_name="post_content",
        ),
        migrations.RenameField(
            model_name="post", old_name="post_unlikes", new_name="post_dislikes",
        ),
        migrations.RenameField(model_name="post", old_name="user", new_name="user_id",),
        migrations.RenameField(
            model_name="postcomments", old_name="post", new_name="post_id",
        ),
        migrations.RenameField(
            model_name="postdownload", old_name="post", new_name="post_id",
        ),
        migrations.RenameField(
            model_name="postdownload", old_name="user", new_name="user_id",
        ),
        migrations.RenameField(
            model_name="userfollower", old_name="folow_date", new_name="follow_date",
        ),
        migrations.RenameField(
            model_name="userfollower", old_name="user", new_name="user_followed",
        ),
        migrations.AddField(
            model_name="post",
            name="tag_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="kuhub.tags"
            ),
        ),
        migrations.AddField(
            model_name="postcomments",
            name="comment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date commented"
            ),
        ),
        migrations.AlterField(
            model_name="postcomments",
            name="comment",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(name="PostTags",),
        migrations.DeleteModel(name="UserComment",),
        migrations.AddField(
            model_name="postreport",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kuhub.post"
            ),
        ),
    ]
