# Generated by Django 4.2.7 on 2023-11-14 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kuhub.subject",
            ),
        ),
    ]
