# Generated by Django 4.2.4 on 2023-11-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupevent',
            name='requests_id',
        ),
    ]
