# Generated by Django 4.2.5 on 2023-10-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0002_postreport_remove_usercomment_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="user_id", new_name="username",
        ),
        migrations.RemoveField(model_name="postdownload", name="user_id",),
    ]
