# Generated by Django 4.2.4 on 2023-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0002_remove_groupevent_requests_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='show_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
