# Generated by Django 4.2.7 on 2023-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0002_alter_postdownload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
