# Generated by Django 4.2.4 on 2023-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0003_groupevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='event_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
