# Generated by Django 4.2.7 on 2023-11-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0003_alter_post_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subject_id",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="kuhub.subject",
            ),
        ),
    ]
