# Generated by Django 4.2.7 on 2023-11-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0002_task_event_alter_task_status"),
        ("kuhub", "0003_alter_profile_display_photo"),
    ]

    operations = []
