# Generated by Django 4.2.5 on 2023-10-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0003_rename_user_id_post_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postdownload",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="downloads",
                to="kuhub.post",
            ),
        ),
    ]
