# Generated by Django 4.2.4 on 2023-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0004_groupevent_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='requests_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
