# Generated by Django 4.2.7 on 2023-11-09 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kuhub', '0005_postdownload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_description', models.CharField(max_length=255)),
                ('group_member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('group_tags', models.ManyToManyField(to='kuhub.tags')),
            ],
        ),
    ]
