# Generated by Django 4.2.7 on 2023-11-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0005_postcomments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='report_count',
            field=models.IntegerField(default=1),
        ),
    ]
