# Generated by Django 4.2.7 on 2023-11-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0005_postdownload_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=100)),
                ("name_eng", models.CharField(max_length=255)),
                ("name_th", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=10)),
                ("hour", models.CharField(max_length=10)),
                ("faculty", models.CharField(max_length=255)),
            ],
        ),
    ]
