# Generated by Django 4.2.7 on 2023-11-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0006_remove_post_post_dislikes_remove_post_post_likes_and_more"),
        ("kuhub", "0006_subject"),
    ]

    operations = []
