# Generated by Django 4.2.4 on 2023-11-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0006_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupevent',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupevent',
            name='requests_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
