# Generated by Django 4.2.7 on 2023-11-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0005_postcomments_username"),
        ("kuhub", "0007_alter_groupevent_link_alter_groupevent_requests_id"),
    ]

    operations = []
