# Generated by Django 4.2.7 on 2023-11-09 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0007_groupcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_date',
            field=models.DateField(default=datetime.date(2023, 11, 10)),
        ),
    ]
