# Generated by Django 4.2.7 on 2023-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/store/profile_photos/'),
        ),
    ]
