# Generated by Django 4.2.4 on 2023-11-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0006_alter_postreport_report_count'),
        ('kuhub', '0008_merge_20231121_1419'),
    ]

    operations = [
    ]
