# Generated by Django 4.2.7 on 2023-11-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0008_group_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='GroupCreate',
        ),
        migrations.AddField(
            model_name='group',
            name='group_password',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kuhub.grouppassword'),
        ),
    ]
