# Generated by Django 4.2.7 on 2023-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0009_merge_20231122_2030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_photo",
            field=models.ImageField(
                blank=True,
                default="kuhub\\static\\images\\default_profile.jpg",
                null=True,
                upload_to="media/store/profile_photos/",
            ),
        ),
    ]
