# Generated by Django 4.2.4 on 2023-11-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0007_merge_20231111_2228'),
        ('kuhub', '0009_alter_profile_display_photo'),
    ]

    operations = [
    ]
