# Generated by Django 4.2.7 on 2023-11-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0009_grouppassword_delete_groupcreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_password',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuhub.grouppassword'),
        ),
    ]
