# Generated by Django 4.2.4 on 2023-11-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0009_merge_20231124_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_calendar',
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_photo',
            field=models.ImageField(blank=True, default='kuhub\\static\\images\\default_profile.jpg', null=True, upload_to='media/store/profile_photos/'),
        ),
    ]
