# Generated by Django 4.2.7 on 2023-11-11 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuhub', '0010_alter_group_group_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='create_date',
            field=models.DateField(default=datetime.date(2023, 11, 11)),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_tags',
            field=models.ManyToManyField(to='kuhub.grouptags'),
        ),
    ]
