# Generated by Django 4.2.7 on 2023-11-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kuhub", "0010_merge_20231111_2338"),
        ("kuhub", "0011_grouptags_alter_group_create_date_and_more"),
    ]

    operations = []
